/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { TripCreateNestedManyWithoutUsersInput } from "./TripCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { ListingWhereUniqueInput } from "../../listing/base/ListingWhereUniqueInput";
import { WishlistCreateNestedManyWithoutUsersInput } from "./WishlistCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => TripCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TripCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TripCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  trips?: TripCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ListingWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ListingWhereUniqueInput)
  @IsOptional()
  @Field(() => ListingWhereUniqueInput, {
    nullable: true,
  })
  user_Id?: ListingWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => WishlistCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WishlistCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WishlistCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  wishlists?: WishlistCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
